[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hidroaccess"
version = "1.0.0"
authors = [
  { name = "SEU NOME AQUI", email = "seu-email@exemplo.com" },
]
description = "Cliente Python para a API HidroWebService da ANA"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp>=3.11.11",
    "requests>=2.32.3",
    "python-dotenv>=1.0.1",
    "pandas>=2.2",
    "pyarrow>=17.0",
]

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]
